name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install linux dependecies
        run: sudo apt-get install -y libfontconfig libfontconfig1-dev
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: cargo rust version
        run: |
          cargo --version
          rustc --version
      - name: Check that code can compile
        run: cargo check
